export const ELEMENT_LAYERS = {
  TOP: 2147483646,
  HIGH: 10,
  MEDIUM: 5,
  LOW: 1,
  BOTTOM: 0,
  HIDDEN: -1,
} as const;

export const COMPONENT_LAYERS = {
  TOOLTIPS: ELEMENT_LAYERS.HIGH,
  POPOVERS: ELEMENT_LAYERS.HIGH,
  MODALS: ELEMENT_LAYERS.MEDIUM,
  FLOATS: ELEMENT_LAYERS.LOW,
} as const;
